# Generated by Django 4.0.4 on 2022-05-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nomlanishi')),
                ('discrition', models.TextField(max_length=5000, verbose_name="Ma'lumot")),
                ('image', models.ImageField(upload_to='Post/', verbose_name='Rasm')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Kiritish vaqti')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='Yangilanish vaqti')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
            },
        ),
    ]
