# Generated by Django 4.0.4 on 2022-05-02 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0002_post_author_post_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tarif')),
                ('price', models.PositiveIntegerField(verbose_name='Narx')),
                ('is_active', models.BooleanField(default=False, verbose_name='Faol')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Kiritish vaqti')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='Yangilanish vaqti')),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricing',
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nomlanishi')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Kiritish vaqti')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='Yangilanish vaqti')),
            ],
            options={
                'verbose_name': 'Requirements',
                'verbose_name_plural': 'Requirements',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mualif'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Tekshirilgan'),
        ),
    ]
