# Generated by Django 4.0.4 on 2022-05-02 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_pricing_requirements_alter_post_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirements',
            new_name='Service',
        ),
        migrations.AddField(
            model_name='pricing',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Blog.service', verbose_name='Xizmat'),
            preserve_default=False,
        ),
    ]
