# Generated by Django 4.0.4 on 2022-05-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_rename_requirements_service_pricing_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='service',
        ),
        migrations.AddField(
            model_name='pricing',
            name='service',
            field=models.ManyToManyField(to='Blog.service', verbose_name='Xizmat'),
        ),
    ]
